import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import {Toaster} from 'react-hot-toast'

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TimeTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster
              position="top-right"
              reverseOrder={true}
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
